import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'
import Logos from '../components/Logos'
import Navbar from '../components/Navbar'
import Frameworks from '../components/Frameworks'
import { GraphQLClient, gql } from 'graphql-request'
import ProjectPost from '../components/ProjectPost'
import Contact from '../components/Contact'
import About from '../components/About'
import { motion } from 'framer-motion'


const endpoint = new GraphQLClient('https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/clbukk0lj2sh801uk6syyh0f9/master');

const Query = 
gql`{
  projects {
    id
    title
    excerpt
    slug
    livesite
    github
    image {
      url
    }
    stack {
      url 
      width
      height
    }
  }
}
`;

export async function getStaticProps() {
  const {projects} = await endpoint.request(Query);
  return {
    props: {
      projects,
    },
  }
}


export default function Home({projects}) {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    setIsVisible(true);
  }, []);

  return (
    <>
      <Head>
        <title>TimJini Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Hero />
        <Frameworks />
        <div className={isVisible ? 'showx' : 'hiddenx'}>
        {projects.map((project) => (
          <ProjectPost 
            key={project.id} 
            title={project.title}
            excerpt={project.excerpt}
            image={project.image}
            slug={project.slug}
            stack={project.stack}
            livesite={project.livesite}
            github={project.github}
            className="card"

             />
        ))}
        </div>
        <About />
        <Contact />
      
      </main>
    </>
  )
}
