import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'
import Logos from '../components/Logos'
import Navbar from '../components/Navbar'
import Frameworks from '../components/Frameworks'
import { GraphQLClient, gql } from 'graphql-request'
import ProjectPost from '../components/ProjectPost'
import Contact from '../components/Contact'
import About from '../components/About'

const endpoint = new GraphQLClient('https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/clbukk0lj2sh801uk6syyh0f9/master');

const Query = 
gql`{
  projects {
    id
    title
    excerpt
    slug
    github
    livesite
    image {
      url
    }
    stack {
      url 
      width
      height
    }
  }
}
`;

export async function getStaticProps() {
  const {projects} = await endpoint.request(Query);
  return {
    props: {
      projects,
    },
  }
}


export default function Home({projects}) {
  return (
    <>
      <Head>
        <title>TimJini Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"></link>
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Hero />
        <Frameworks />
        <div>
        {projects.map((project) => (
          <ProjectPost 
            key={project.id} 
            title={project.title}
            excerpt={project.excerpt}
            image={project.image}
            slug={project.slug}
            stack={project.stack}

             />
        ))}
        </div>
        <About />
        <Contact />
      
      </main>
    </>
  )
}
